import json
from pathlib import Path

out = []
def add(text, lang, cat, sev, note):
    text = " ".join(text.lower().split())
    out.append({"text": text, "language": lang, "category": cat, "severity": sev, "note": note})

# ---------- Gambling: brands x actions (en + pidgin) ----------
brands = ["bet9ja","sportybet","betking","1xbet","msport","betano","nairabet","betway","22bet","bangbet","paripesa","betbonanza","merrybet","accessbet","naijabet","wazobet","livescorebet","betpawa","hollywoodbets","aviator","sporty","baba ijebu","zoom score","betnaija","frapapa","bet365","betfair"]
gpat = [("{b} booking code","review"),("{b} code","review"),("drop {b} code","review"),("stake on {b}","review"),("i stake for {b}","high"),("load my {b}","review"),("fund my {b}","review"),("{b} cash out","review"),("cash out on {b}","review"),("{b} wallet","low"),("{b} don pay me","review"),("{b} eat my money","review"),("i lose for {b}","review"),("deposit for {b}","review"),("withdraw from {b}","review"),("{b} odds","review"),("{b} ticket","review"),("my {b} ticket","review"),("{b} account","low"),("open {b} account","review"),("{b} bonus","low"),("{b} promo code","low"),("play {b}","review"),("i dey play {b}","review")]
for b in brands:
    for p, s in gpat:
        add(p.format(b=b), "pidgin", "Gambling", s, "brand action pattern")
extra_g = [("i don stake my pocket money","high"),("i stake my feeding money","high"),("i use my school fees play bet","high"),("i don lose my school fees for bet","high"),("borrow me money make i stake","high"),("lend me money for bet","review"),("i go pay you back after i cash out","review"),("sure odds for today","review"),("sure banker","review"),("fixed match","review"),("fixed game","review"),("correct score for tonight","review"),("accumulator ticket","review"),("acca of the day","review"),("virtual football","review"),("virtual game don finish my money","high"),("aviator crash","review"),("crash game","review"),("i dey play aviator","review"),("aviator don eat my money","high"),("play lotto","low"),("buy lotto ticket","low"),("baba ijebu result","review"),("ghana lotto","review"),("nap 2","review"),("perm 3","review"),("stake and win","review"),("gamble my money","high"),("i be gambler","review"),("i can't stop betting","high"),("i no fit stop betting","high"),("betting don spoil me","high"),("i dey owe because of bet","high"),("bet don finish me","high"),("cash out fast","low"),("i win small for bet","low"),("who get sure game","review"),("give me sure game","review"),("send me game","low"),("odds don burst","review"),("my ticket cut","review"),("one game cut my ticket","review")]
for t, s in extra_g: add(t, "pidgin", "Gambling", s, "gambling idiom")

# ---------- Substance: drugs x verbs (pidgin) ----------
drugs = ["loud","kush","skunk","colos","colorado","arizona","gbana","wee wee","weed","molly","mdma","codeine","tramol","tramadol","refnol","rophynol","lean","purple drank","crystal meth","meth","mkpuru mmiri","monkey tail","gutter water","cocaine","coke","shisha","vape","hookah","ecstasy","exol","pills","tabs"]
dpat = [("who get {d}","high"),("where i fit get {d}","high"),("sell me {d}","high"),("buy {d}","high"),("i wan buy {d}","high"),("bring {d}","high"),("i don smoke {d}","high"),("make we smoke {d}","high"),("make we blaze {d}","high"),("{d} plug","high"),("plug for {d}","high"),("i dey high on {d}","high"),("i don take {d}","high"),("{d} for sale","high"),("i need {d}","review"),("get me {d}","high"),("{d} don land","review"),("roll {d}","high"),("we dey do {d}","high"),("hook me up with {d}","high"),("{d} dey your side","review"),("how much for {d}","high"),("i dey sell {d}","high"),("{d} wey i take","review")]
soft = {"shisha","vape","hookah"}
for d in drugs:
    for p, s in dpat:
        sev = "low" if d in soft else s
        add(p.format(d=d), "pidgin", "Substance Use", sev, "drug verb pattern")
extra_s = [("mix codeine with sprite","high"),("codeine and sprite","high"),("cough syrup to get high","high"),("drink codeine","high"),("tutolin","review"),("benylin with codeine","high"),("sniff glue","high"),("sniff solution","high"),("sniff pit toilet","high"),("smoke lizard dung","high"),("smoke pawpaw leaf","review"),("zakami","review"),("gum sniffing","high"),("i dey chase high","high"),("i wan get high","high"),("make we get high","high"),("i don high","review"),("i dey trip","review"),("i wan trip","review"),("popping pills","high"),("pop some tabs","high"),("drunk and high","review"),("i dey drink to forget","review"),("get me drunk","review"),("bring alcohol come school","review"),("sneak alcohol","review"),("mix drugs and alcohol","high")]
for t, s in extra_s: add(t, "pidgin", "Substance Use", s, "substance idiom")

# ---------- Sexual content / sextortion / grooming (pidgin + en) ----------
parts = ["nudes","naked pic","naked picture","boobs pic","bum pic","pussy pic","dick pic","body pic","private part","bathroom pic","towel pic","bra pic","pant pic","naked video","bath video","sex video","boobs","nyash","kpekus","toto"]
spat = [("send me your {x}","high"),("send your {x}","high"),("show me your {x}","high"),("i go leak your {x}","high"),("i go post your {x}","high"),("pay me or i share your {x}","high"),("send {x} or i post","high"),("snap your {x}","high"),("i wan see your {x}","high"),("send {x} make i see","high"),("your {x} dey sweet","review"),("i don see your {x}","review"),("delete my {x}","review"),("who leak my {x}","review")]
for x in parts:
    for p, s in spat:
        add(p.format(x=x), "pidgin", "Sexual Content", s, "sextortion pattern")
groom = [("our little secret","high"),("this na our secret","high"),("no tell your mummy","high"),("no tell your parents about us","high"),("don't tell your parents about us","high"),("you look mature for your age","high"),("you too mature for your age","high"),("how old are you sef","review"),("are you home alone","review"),("you dey house alone","review"),("come see me alone","high"),("come my house alone","high"),("i go buy you phone if you come","high"),("i go send you money if you send","high"),("send location make i come","review"),("video call now naked","high"),("remove your cloth on camera","high"),("off your cloth for camera","high"),("make we do video sex","high"),("sex chat with me","high"),("let's sext","high"),("make we sext","high"),("you be virgin","review"),("i go teach you sex","high"),("come make i touch you","high"),("let me touch you","high"),("sit on my lap","review"),("i love you like woman","review"),("be my small wife","high"),("sugar daddy dey pay","review"),("i go be your sugar daddy","high"),("hook up tonight","review"),("come for hookup","review"),("runs girl","review"),("do runs","review"),("olosho price","high"),("how much for short time","high"),("short time and all night","high"),("knack tonight","high"),("make we knack","high"),("i wan knack you","high"),("knacking","review"),("chop your toto","high"),("suck your breast","high"),("i wan lick you","high"),("send pic without cloth","high"),("pic without bra","high"),("shift your pant small","high"),("open your leg for camera","high"),("blowjob","high"),("give me head","high"),("handjob","high"),("threesome","high"),("porn link","high"),("send porn","high"),("watch porn together","high"),("xvideos","high"),("pornhub","high"),("xnxx","high"),("onlyfans link","review"),("dm for content","review"),("premium snap","review"),("nude leak","high"),("leaked video of","review")]
for t, s in groom: add(t, "pidgin", "Sexual Content", s, "grooming or explicit")

# ---------- Violence: threats x when (pidgin) ----------
threats = [("i go beat you","review"),("i go wire you","review"),("i go stab you","high"),("i go shoot you","high"),("i go kill you","high"),("i go break your head","high"),("i go scatter your face","high"),("i go deal with you","review"),("we go jump you","high"),("we go waylay you","high"),("i go cut you","high"),("i go burn your house","high"),("i go use bottle on you","high"),("i go collect your life","high"),("i go slap you","low"),("i go disgrace you","low"),("i go finish you","high"),("i go send boys for you","high"),("boys go visit you","high"),("i know where you dey stay","review")]
when = ["","after school","tomorrow","for gate","for road","for hostel","today","when school close","make you wait"]
for t, s in threats:
    for w in when:
        add(f"{t} {w}".strip(), "pidgin", "Violence", s, "threat pattern")
cult = [("join eiye","high"),("join aye","high"),("join buccaneer","high"),("join black axe","high"),("join vikings","high"),("join confra","high"),("cult initiation","high"),("initiation tonight","high"),("blend tonight","review"),("i don blend","review"),("aye confraternity","high"),("eiye confraternity","high"),("black axe","high"),("neo black movement","high"),("supreme vikings","high"),("buccaneers","review"),("we go show you pepper","review"),("carry gun come","high"),("bring cutlass","high"),("bring axe come school","high"),("i get gun","high"),("pistol dey my bag","high"),("knife dey my bag","high"),("i carry knife come school","high"),("gang fight after school","high"),("street fight today","review"),("come fight me","review"),("i go fight you","review"),("beat am well well","review"),("jump am for road","high"),("waylay am","high"),("stone am","review"),("burn am alive","high"),("kill am","high"),("we go kill am","high"),("wire am well","review")]
for t, s in cult: add(t, "pidgin", "Violence", s, "cult or weapon")

# ---------- Self harm idioms (pidgin + en) ----------
sh = [("i wan end am","high"),("i wan end everything","high"),("i no wan wake up tomorrow","high"),("i wish i no dey alive","high"),("e for better if i die","high"),("make i just die","high"),("i go kill myself tonight","high"),("i dey plan to end am","high"),("i don write my note","high"),("goodbye everyone","review"),("no be my fault if i die","high"),("i wan sleep and no wake","high"),("i don tire for this life","high"),("nobody go miss me","review"),("nobody go miss me if i die","high"),("i dey cut myself","high"),("i don cut again","high"),("razor dey my hand","high"),("i swallow plenty tablets","high"),("i take overdose","high"),("overdose tonight","high"),("unalive myself","high"),("i wan unalive myself","high"),("unalive","review"),("kms","high"),("wanna kms","high"),("i wanna kms","high"),("sewerslide","high"),("self delete","high"),("i wan self delete","high"),("i wan disappear forever","high"),("i wan vanish from this world","high"),("this world no need me","high"),("everybody go dey fine without me","high"),("i be burden","review"),("i am a burden","review"),("i don give up on life","high"),("i give up on everything","review"),("life no get meaning","review"),("what is the point of living","high"),("wetin be the point of living","high"),("i no see reason to live","high"),("i just wan die","high"),("i wan die abeg","high"),("i wan die o","high"),("make god take my life","high"),("i pray make i no wake","high"),("i go jump from this building","high"),("i go jump for third mainland","high"),("i go drink sniper","high"),("sniper dey my room","high"),("i buy sniper","high"),("rat poison dey my hand","high"),("i go hang myself","high"),("rope dey ready","high"),("i dey hurt myself","high"),("hurting myself again","high"),("i burn myself","high"),("i punch wall till i bleed","review"),("i starve myself as punishment","high"),("i deserve pain","review"),("i hate being alive","high"),("i hate my life so much","review"),("tired of living","high"),("tired of everything","review"),("i no fit do this again","review"),("i can't do this anymore","review"),("end it tonight","high"),("ending it tonight","high"),("last message","review"),("this is goodbye","high"),("if i no reply again na because","high"),("delete my account after i die","high")]
for t, s in sh: add(t, "pidgin", "Self-Harm", s, "self harm idiom")

# ---------- Eating disorders (pidgin + en) ----------
ed = [("i no chop since morning","review"),("i no go chop today","review"),("i no chop for two days","high"),("i dey fast make i slim","high"),("make i purge am","high"),("i vomit am after i chop","high"),("i throw up after eating","high"),("i too fat abeg","review"),("i wan thin like model","review"),("safe food only","review"),("safe foods","review"),("fear food","review"),("cw","low"),("ugw","review"),("gw","low"),("current weight goal weight","review"),("meanspo","high"),("thinspo","high"),("bonespo","high"),("pro ana","high"),("pro mia","high"),("ana buddy","high"),("mia buddy","high"),("ana coach","high"),("fasting 3 days","high"),("3 day fast","high"),("water fast","high"),("dry fast","high"),("chew and spit","high"),("laxatives make i lose weight","high"),("laxatives to lose weight","high"),("diet pills","review"),("slimming tea to purge","high"),("count every calorie","review"),("500 calories a day","high"),("under 500 cals","high"),("body check","review"),("body checking","review"),("i hate my body","review"),("my thighs too big","low"),("thigh gap","review"),("collarbones showing","review"),("hip bones showing","review"),("i skip breakfast and lunch","review"),("skip dinner again","review"),("hide food from mummy","high"),("i dey hide food","review"),("i pour my food away","review"),("i lie say i don chop","review"),("purge after party","high"),("binge and purge","high"),("bulimia","high"),("anorexic","high"),("i wan be anorexic","high"),("ed twt","review"),("edtwt","review"),("restricting again","high"),("restrict today","review"),("fasting till i faint","high"),("i faint from hunger","review"),("nothing tastes as good as skinny feels","high")]
for t, s in ed: add(t, "pidgin", "Eating Disorders", s, "eating disorder idiom")

# ---------- Graphic content (pidgin + en) ----------
gr = [("beheading video","high"),("dem cut him head","high"),("see the dead body","review"),("dead body video","review"),("accident video wey blood full","review"),("ritual killing video","high"),("watch am burn alive","high"),("burnt alive video","high"),("gore video","high"),("execution video","high"),("dem shoot am for head video","high"),("corpse video","review"),("murder video","high"),("suicide video","high"),("hanging video","high"),("dead pikin video","high"),("blood everywhere video","review"),("slaughter video","high"),("dem butcher am","high"),("cut throat video","high"),("necklacing video","high"),("jungle justice video","high"),("mob burn thief video","high"),("bandits video","review"),("massacre video","high"),("bomb blast video","review"),("plane crash bodies","review"),("drowned body","review"),("body bag video","review"),("morgue video","review"),("autopsy video","review"),("animal cruelty video","review"),("dog fight video","review"),("gore site","high"),("liveleak","high"),("bestgore","high"),("watchpeopledie","high"),("nsfl","high"),("not safe for life","review"),("headless body","high"),("brain commot","high"),("intestine commot","high"),("blood full ground","review"),("dem stab am video","high")]
for t, s in gr: add(t, "pidgin", "Graphic Content", s, "graphic idiom")

# ---------- Hate speech patterns (pidgin + en) ----------
groups = ["hausa people","igbo people","yoruba people","fulani","northerners","southerners","muslims","christians","nyamiri","ofe mmanu","gambari","gay people","tiv people","ijaw people","edo people","calabar people"]
preds = [("all {g} are thieves","review"),("all {g} are terrorists","high"),("all {g} are dirty","review"),("{g} are animals","high"),("{g} no be human","high"),("all {g} should die","high"),("kill all {g}","high"),("{g} must go","review"),("{g} are ritualists","review"),("all {g} are cows","review"),("i hate {g}","review"),("{g} are useless","review"),("{g} smell","review"),("burn all {g}","high"),("wipe out {g}","high")]
for g in groups:
    for p, s in preds:
        add(p.format(g=g), "pidgin", "Hate Speech", s, "group hate pattern")

# ---------- Yoruba ----------
yo = {
 "Self-Harm": [("mo ti su aye yi","high"),("aye ti su mi","review"),("mi o fe gbe mo","high"),("ma pa ara mi","high"),("mo fe pa ara mi loni","high"),("ki n ku lo dara","high"),("ko si idi lati wa laaye","high"),("n o ni wa laye lola","high"),("mo fe lo kuro ni aye yi","high"),("mo n ge ara mi","high"),("mo ge owo mi","high"),("mo fe mu oogun ju","high"),("emi ko wulo","review"),("ko si eni to nife mi","review"),("o dara ki n ma si","high"),("mo fe ku loni","high"),("mo fe pokunso","high"),("ma so ara mi sinu odo","high"),("mo fe fo lati ori ile","high"),("mo ti re pupo","review"),("aye ko wulo fun mi","high"),("mo fe sun ki n ma ji","high"),("e ma gbagbe mi ti mo ba ku","high"),("mo n fi abe ge ara mi","high")],
 "Violence": [("ma na e","review"),("ma gbe e sanle","review"),("maa fo ori e","high"),("ma fun e ni abe","high"),("obe wa lowo mi","high"),("ma gun e","high"),("ma ba e ja","review"),("ma yin e ni ibon","high"),("ma ge e","high"),("wa ku loni","high"),("iku n bo wa ba e","high"),("ma pa e loni","high"),("ma lu e daadaa","review"),("a ma duro de e leyin ile iwe","high"),("awon boys ma wa ba e","high"),("ma fi igo lu e","high"),("ma jo ile yin","high"),("ibon wa ninu apo mi","high"),("obe wa ninu apo mi","high"),("mo wa ninu confra","high"),("darapo mo aye","high"),("darapo mo eiye","high")],
 "Sexual Content": [("fi oyan e han mi","high"),("ran foto ihoho","high"),("fi ara e han mi","high"),("mo fe ba e sun","high"),("je ka sun po","high"),("fi idi e han mi","high"),("ran mi ni nudes","high"),("wa ba mi sun","high"),("oko mi ti le","high"),("fi obo e han","high"),("je ka do","high"),("mo fe do e","high"),("fi ara e han lori camera","high"),("bo aso e lori camera","high"),("ma so fun mama e","high"),("asiri wa ni","high"),("o ti dagba ju ojo ori e","review"),("iwo nikan lo wa nile","review"),("wa ile mi nikan","high"),("ma ra foonu fun e ti o ba wa","high"),("olosho","high"),("ashewo","high"),("fi ese e sile","high"),("ma fi owo kan e","high")],
 "Substance Use": [("mu igbo","high"),("fa igbo","high"),("ta igbo","high"),("ra igbo fun mi","high"),("wa mu igbo","high"),("tani o ni igbo","high"),("mu tramol","high"),("ta tramol","high"),("ra tramol","high"),("mu codeine","high"),("codeine ati sprite","high"),("mu colos","high"),("ta colos","high"),("mu sk","high"),("mu kush","high"),("mu loud","high"),("mu ogogoro","review"),("mu oti ju","review"),("mo ti mu oti","review"),("je ka mu igbo","high"),("igbo wa lowo mi","high"),("mo fe ga","review"),("je ka ga","review"),("mo ti ga","review")],
 "Gambling": [("ta bet","review"),("gbe bet","review"),("mo ta bet","review"),("mo fi owo ile iwe ta bet","high"),("ta sporty","review"),("gbe game","review"),("mo padanu owo mi ninu bet","high"),("owo bet","review"),("ta parlay","review"),("fun mi ni code","review"),("fun mi ni booking code","review"),("mo fi owo ounje ta bet","high"),("bet ti je owo mi","high"),("mo ti win bet","review"),("ta virtual","review"),("mo n ta bet lojojumo","high"),("ya mi lowo ki n ta bet","high"),("mo ti gba cash out","review"),("game to daju","review"),("fun mi ni game to daju","review"),("mo fi allowance mi ta bet","high"),("mi o le da bet duro","high")],
 "Eating Disorders": [("mi o ni je","review"),("mi o je ounje lati ana","high"),("mo fe bi","high"),("mo n bi leyin ti mo ba jeun","high"),("mo ti sanra ju","review"),("mo fe di tinrin","review"),("mi o je ohunkohun loni","review"),("ebi n pa mi sugbon mi o ni je","high"),("mo n gbawe ki n le ru","high"),("mo fe ru","review"),("mo ko ounje mi sile","review"),("mo pa ounje mi mo","review"),("mo n ka calorie","review"),("ara mi buru","review"),("mo korira ara mi","review"),("mi o ni je titi ma fi daku","high"),("mo n lo laxative ki n le ru","high"),("mo n puro pe mo ti jeun","review")],
 "Graphic Content": [("fidio eje","review"),("won ge ori e","high"),("oku eniyan","review"),("fidio iku","review"),("wo bi won se pa a","high"),("eje kun ibe","review"),("fidio ijamba","review"),("won sun un laaye","high"),("fidio ti won ti pa eniyan","high"),("fidio ipaniyan","high"),("wo oku yi","review"),("won be ori e","high"),("fidio ti won ti gun eniyan","high"),("fidio jungle justice","high"),("won jo ole laaye","high"),("oku omo kekere","high"),("fidio ogun","review"),("fidio bombu","review")],
 "Hate Speech": [("gbogbo awon hausa ni ole","review"),("gbogbo awon igbo ni ole","review"),("gbogbo awon musulumi ni onijagidijagan","high"),("gbogbo awon kristeni ni eleke","review"),("gbogbo awon fulani ni apaniyan","high"),("awon gambari","review"),("gbogbo gambari","review"),("awon eranko ni won","high"),("won ko ye ki won wa laaye","high"),("e pa gbogbo won","high"),("awon kobokobo","review"),("gbogbo awon ajokutamamumi","review"),("won ko ni ye","review"),("mo korira awon hausa","review"),("mo korira awon igbo","review"),("mo korira awon yoruba","review"),("awon omo ale ni won","review"),("gbogbo awon adua ni oloriburuku","review")],
}
for cat, items in yo.items():
    for t, s in items: add(t, "yoruba", cat, s, "yoruba seed 2")

# ---------- Hausa ----------
ha = {
 "Self-Harm": [("na gaji da rayuwa","high"),("rayuwa ta gundure ni","review"),("ba na son in rayu","high"),("gara in mutu","high"),("zan sha maganin kashe kai","high"),("ina yanke hannuna","high"),("babu wanda yake so na","review"),("in mutu ya fi","high"),("ba ni da amfani","review"),("zan bar duniya","high"),("zan rataye kaina","high"),("zan sha guba","high"),("zan yi tsalle daga gini","high"),("ba zan farka ba gobe","high"),("ina son in bace","high"),("kowa zai fi dadi idan na mutu","high"),("na rubuta wasika ta ta karshe","high"),("wannan bankwana ne","high"),("na gaji da komai","review"),("babu amfanin rayuwa","high"),("ina cutar da kaina","high"),("ina son in kashe kaina yau","high")],
 "Violence": [("zan doke ka","review"),("zan yanka ka","high"),("zan harbe ka","high"),("wuka na na hannu","high"),("zan fasa kanka","high"),("za ka mutu yau","high"),("zan daki ka","review"),("sai mun fada","review"),("zan sare ka","high"),("zan kona gidan ka","high"),("zan kashe ka yau","high"),("ina da bindiga","high"),("bindiga tana jakata","high"),("wuka tana jakata","high"),("yara za su zo maka","high"),("za mu jira ka bayan makaranta","high"),("zan buge ka da kwalba","high"),("zan yi maka rauni","high"),("zan karya kashin ka","high"),("mun shirya fada yau","review"),("zan sa a doke ka","high"),("zan yi maka ba dadi","review")],
 "Sexual Content": [("aiko min hoton tsiraici","high"),("nuna min nonon ki","high"),("aiko min nudes","high"),("ina son in kwana da ke","high"),("mu yi jima'i","high"),("nuna min jikin ki","high"),("aiko hoton jikinki","high"),("zo mu kwanta","high"),("ina so in taba ki","high"),("cire kayanki a kamara","high"),("nuna min a bidiyo","high"),("kada ki gaya wa mahaifiyarki","high"),("sirrin mu ne","high"),("kin girma fiye da shekarunki","review"),("kina gida ke kadai","review"),("zo gidana ke kadai","high"),("zan siya miki waya idan kin zo","high"),("karuwa","high"),("mu yi lalata","high"),("bude kafafunki","high"),("zan biya ki idan kin aiko","high"),("zan yada hotonki idan ba ki biya ba","high"),("zan fallasa hotonki","high"),("aiko min bidiyon ki tsirara","high")],
 "Substance Use": [("taba wiwi","high"),("sha wiwi","high"),("sayar da wiwi","high"),("sha tramol","high"),("sayi tramol","high"),("sha kwaya","high"),("sayi kwaya","high"),("sha codeine","high"),("codeine da sprite","high"),("shan solisho","high"),("shan gum","high"),("sha sk","high"),("sha colos","high"),("sayar min da wiwi","high"),("ina neman wiwi","high"),("wa ke da wiwi","high"),("ina neman kwaya","high"),("mu sha wiwi","high"),("ina cikin maye","review"),("zan yi maye","review"),("na sha maye","review"),("shan zakami","review"),("sha giya","review"),("mu sha giya","review"),("ina son in yi maye","review"),("kwaya ta kama ni","high")],
 "Gambling": [("na yi caca","review"),("zan yi caca","review"),("na sa kudin makaranta caca","high"),("na rasa kudi na a caca","high"),("aiko min booking code","review"),("ban win ba","low"),("na yi bet","review"),("zan sa kudi bet","review"),("na sa kudin abinci bet","high"),("bet ya cinye kudina","high"),("ba zan iya daina caca ba","high"),("ba ni rance in yi bet","high"),("ka ba ni sure game","review"),("wasan da ya tabbata","review"),("na yi sporty","review"),("na yi bet9ja","review"),("na ci cash out","review"),("ticket na ya yanke","review"),("na sa allowance na bet","high"),("ina caca kullum","high"),("na yi virtual","review"),("aviator ya cinye kudina","high")],
 "Eating Disorders": [("ba zan ci abinci ba","review"),("ina jin kiba","review"),("ina son in rame","review"),("na yi amai bayan cin abinci","high"),("ban ci abinci ba tun jiya","high"),("ina azumi don in rame","high"),("na yi kiba sosai","review"),("zan daina cin abinci","high"),("ina boye abinci","review"),("na zubar da abincina","review"),("ina karya cewa na ci","review"),("ina kirga calorie","review"),("ba zan ci ba har sai na suma","high"),("ina shan maganin bayan gida don in rame","high"),("ina kin jikina","review"),("cinyata sun yi girma","low"),("ban ci abinci ba kwana biyu","high")],
 "Graphic Content": [("bidiyon jini","review"),("an yanke kansa","high"),("gawa","review"),("bidiyon mutuwa","review"),("an kashe shi a bidiyo","high"),("jini ko ina","review"),("bidiyon hatsari","review"),("an kona shi da rai","high"),("bidiyon kisa","high"),("bidiyon fille kai","high"),("duba gawar nan","review"),("an yanka shi a bidiyo","high"),("bidiyon jungle justice","high"),("an kona barawo da rai","high"),("gawar yaro","high"),("bidiyon yaki","review"),("bidiyon bam","review"),("kai babu jiki","high")],
 "Hate Speech": [("duk kafirai","review"),("yan iska","review"),("duk inyamurai barayi ne","review"),("duk yarbawa barayi ne","review"),("duk kiristoci makiya ne","high"),("duk musulmai yan ta'adda ne","high"),("dabbobi ne su","high"),("bai kamata su rayu ba","high"),("a kashe su duka","high"),("ina kin inyamurai","review"),("ina kin yarbawa","review"),("ina kin hausawa","review"),("duk fulani mahara ne","high"),("arna ne su","review"),("su tafi daga nan","review"),("duk yan kudu barayi ne","review"),("ba mutane ba ne","high"),("a kona su duka","high")],
}
for cat, items in ha.items():
    for t, s in items: add(t, "hausa", cat, s, "hausa seed 2")

# ---------- Igbo ----------
ig = {
 "Self-Harm": [("ike gwuru m ndu a","high"),("achoghi m ibi ndu ozo","high"),("ndu adighi m mma","review"),("ka m nwuo","high"),("aga m anu ogwu","high"),("ana m ebe aka m","high"),("onweghi onye huru m n'anya","review"),("abaghi m uru","review"),("aga m ahapu uwa a","high"),("aga m akwugbu onwe m","high"),("aga m anu nsi","high"),("aga m esi n'ulo elu wufee","high"),("agaghi m eteta echi","high"),("achoro m ifu","high"),("onye obula ga adi mma ma m nwuo","high"),("edere m akwukwo ikpeazu m","high"),("nke a bu nke ikpeazu","high"),("ike gwuru m ihe niile","review"),("ndu enweghi isi","high"),("ana m emeru onwe m ahu","high"),("achoro m inwu taa","high"),("ka chukwu were ndu m","high")],
 "Violence": [("aga m egbu gi","high"),("aga m agbu gi mma","high"),("aga m agba gi egbe","high"),("mma di m n'aka","high"),("aga m akuwa isi gi","high"),("i ga anwu taa","high"),("aga m aku gi ihe","review"),("anyi ga alu ogu","review"),("aga m egbutu gi","high"),("aga m agba ulo gi oku","high"),("enwere m egbe","high"),("egbe di n'akpa m","high"),("mma di n'akpa m","high"),("umu okorobia ga abiara gi","high"),("anyi ga echere gi ma ulo akwukwo gbasaa","high"),("aga m eji karama kuo gi","high"),("aga m emeru gi ahu","high"),("aga m agbaji okpukpu gi","high"),("anyi ga alu ogu taa","review"),("aga m eme ka e tie gi ihe","high"),("aga m eti gi ihe nke oma","review"),("banye n'otu aye","high")],
 "Sexual Content": [("zitere m foto oto","high"),("gosi m ara gi","high"),("zitere m nudes","high"),("achoro m idina gi","high"),("ka anyi mekoo","high"),("gosi m ahu gi","high"),("bia ka anyi dinaa","high"),("achoro m imetu gi aka","high"),("yipu uwe gi na kamera","high"),("gosi m na vidio","high"),("agwala mama gi","high"),("o bu ihe nzuzo anyi","high"),("i toro karia afo gi","review"),("i no n'ulo naani gi","review"),("bia ulo m naani gi","high"),("aga m azutara gi ekwenti ma i bia","high"),("ashawo","high"),("ka anyi mee ihe ojoo","high"),("meghee ukwu gi","high"),("aga m akwu gi ugwo ma i zitere","high"),("aga m ekesa foto gi ma i kwughi ugwo","high"),("aga m ekpughe foto gi","high"),("zitere m vidio gi gba oto","high"),("achoro m irachaa gi","high")],
 "Substance Use": [("ise wiwi","high"),("ire wiwi","high"),("zuta m wiwi","high"),("ise tramol","high"),("zuta tramol","high"),("ise codeine","high"),("codeine na sprite","high"),("ise colos","high"),("ise sk","high"),("ise loud","high"),("nye m wiwi","high"),("onye nwere wiwi","high"),("ana m eri mkpuru mmiri","high"),("mkpuru mmiri","high"),("zuta mkpuru mmiri","high"),("ire mkpuru mmiri","high"),("ka anyi see wiwi","high"),("ana m ese ihe","review"),("achoro m ise ihe","review"),("anu m mmanya karia","review"),("ka anyi nuo mmanya","review"),("ogwu ojoo","review"),("ana m anu ogwu ojoo","high"),("nye m ogwu ojoo","high"),("ise igbo ojoo","high"),("akara m ala","review")],
 "Gambling": [("igba bet","review"),("aga m agba bet","review"),("ejiri m ego akwukwo gbaa bet","high"),("ego m furu na bet","high"),("zitere m booking code","review"),("agbara m bet","review"),("agbara m sporty","review"),("agbara m bet9ja","review"),("ejiri m ego nri gbaa bet","high"),("bet riri ego m","high"),("enweghi m ike ikwusi igba bet","high"),("gbazinye m ego ka m gbaa bet","high"),("nye m egwuregwu doro anya","review"),("egwuregwu doro anya","review"),("enwetara m cash out","review"),("tiketi m dara","review"),("ejiri m allowance m gbaa bet","high"),("ana m agba bet kwa ubochi","high"),("agbara m virtual","review"),("aviator riri ego m","high"),("nye m code","review")],
 "Eating Disorders": [("agaghi m eri nri","review"),("adi m abuba","review"),("achoro m ida ahu","review"),("eribeghi m nri kemgbe unyahu","high"),("ana m agbo agbo mgbe m risiri nri","high"),("ana m ebu onu ka m daa ahu","high"),("abuba m karia","review"),("aga m akwusi iri nri","high"),("ana m ezo nri","review"),("awufuru m nri m","review"),("ana m agha ugha na m riri nri","review"),("ana m agu calorie","review"),("agaghi m eri ruo mgbe m dara","high"),("ana m anu ogwu afo ka m daa ahu","high"),("akporo m ahu m asi","review"),("apata m buru ibu","low"),("eribeghi m nri ubochi abuo","high")],
 "Graphic Content": [("vidio obara","review"),("e bepuru ya isi","high"),("ozu","review"),("vidio onwu","review"),("obara juru ebe ahu","review"),("vidio ihe mberede","review"),("ha gburu ya na vidio","high"),("a kporo ya oku na ndu","high"),("vidio igbu mmadu","high"),("vidio ibepu isi","high"),("lee ozu a","review"),("e gburu ya na vidio","high"),("vidio jungle justice","high"),("ha kporo onye ohi oku na ndu","high"),("ozu nwata","high"),("vidio agha","review"),("vidio bombu","review"),("isi enweghi ahu","high")],
 "Hate Speech": [("ndi awusa niile bu ohi","review"),("ndi yoruba niile bu ohi","review"),("onye ohu","review"),("ndi alakuba niile bu ndi na eyi egwu","high"),("ndi kraist niile bu ndi iro","high"),("ha bu anumanu","high"),("ha ekwesighi idi ndu","high"),("gbuo ha niile","high"),("akporo m ndi awusa asi","review"),("akporo m ndi yoruba asi","review"),("akporo m ndi igbo asi","review"),("ndi fulani niile bu ndi ogbu mmadu","high"),("ha bu ndi ogo mmuo","review"),("ka ha puo ebe a","review"),("ndi ugwu niile bu ohi","review"),("ha abughi mmadu","high"),("kpoo ha niile oku","high"),("ndi ofe mmanu niile","review")],
}
for cat, items in ig.items():
    for t, s in items: add(t, "igbo", cat, s, "igbo seed 2")

# English copies of the pidgin patterns that read as English too
en_extra = [("i want to end it all tonight","Self-Harm","high"),("no one would notice if i was gone","Self-Harm","high"),("i am done with everything","Self-Harm","review"),("planning my exit","Self-Harm","high"),("i took too many pills","Self-Harm","high"),("i cut again last night","Self-Harm","high"),("send nudes or i leak","Sexual Content","high"),("i will leak your nudes","Sexual Content","high"),("pay or i post your pics","Sexual Content","high"),("send a pic in your towel","Sexual Content","high"),("are your parents home","Sexual Content","review"),("this stays between us","Sexual Content","review"),("i will beat you up tomorrow","Violence","high"),("bring a knife to school","Violence","high"),("i have a gun at home","Violence","high"),("we will jump you after school","Violence","high"),("where can i buy weed","Substance Use","high"),("who sells loud","Substance Use","high"),("codeine with sprite","Substance Use","high"),("i staked my school fees","Gambling","high"),("i lost my allowance on bet9ja","Gambling","high"),("send me the booking code","Gambling","review"),("i skipped every meal today","Eating Disorders","review"),("i purged after dinner","Eating Disorders","high"),("watch this beheading","Graphic Content","high"),("video of him burned alive","Graphic Content","high"),("all igbos are thieves","Hate Speech","review"),("all northerners are terrorists","Hate Speech","high")]
for t, c, s in en_extra: add(t, "en", c, s, "english seed 2")

seen = set(); uniq = []
for x in out:
    k = (x["text"], x["language"], x["category"])
    if k in seen: continue
    seen.add(k); uniq.append(x)
Path(__file__).with_name("seed").joinpath("expansion-2.json").write_text(json.dumps(uniq, indent=0, ensure_ascii=False))
import collections
print("generated", len(uniq), collections.Counter(x["language"] for x in uniq))
